üêætrain_main
    EPOCHS: 15
    BATCH_SIZE: 256
    kifu_dir: None
    size: 9
    use_gpu: True
    rl: False
    window_size: 300000
    network_name: DualNet_256_24_semeai
    npz_dir: backup/data_Q50k_semeai
    ddp: True
    rl_num: -1
    rl_datetime: 
    input_opt: 
üêætrain_on_gpu_ddp 2024-10-16 00:50:03.029160
    [20241016_005003] device
    torch.cuda.current_device:  0
    torch.cuda.device_count:  2
    torch.cuda.get_device_name(0):  TITAN RTX
    torch.cuda.get_device_name(1):  TITAN RTX
    torch.cuda.get_device_capability(0):  (7, 5)
    torch.cuda.get_device_capability(1):  (7, 5)
    torch.cuda.get_arch_list():  ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
Training data set : ['backup/data_Q50k_semeai/sl_data_0.npz', 'backup/data_Q50k_semeai/sl_data_1.npz', 'backup/data_Q50k_semeai/sl_data_10.npz', 'backup/data_Q50k_semeai/sl_data_11.npz', 'backup/data_Q50k_semeai/sl_data_12.npz', 'backup/data_Q50k_semeai/sl_data_13.npz', 'backup/data_Q50k_semeai/sl_data_14.npz', 'backup/data_Q50k_semeai/sl_data_15.npz', 'backup/data_Q50k_semeai/sl_data_16.npz', 'backup/data_Q50k_semeai/sl_data_17.npz', 'backup/data_Q50k_semeai/sl_data_18.npz', 'backup/data_Q50k_semeai/sl_data_2.npz', 'backup/data_Q50k_semeai/sl_data_3.npz', 'backup/data_Q50k_semeai/sl_data_4.npz', 'backup/data_Q50k_semeai/sl_data_5.npz']
Testing data set  : ['backup/data_Q50k_semeai/sl_data_6.npz', 'backup/data_Q50k_semeai/sl_data_7.npz', 'backup/data_Q50k_semeai/sl_data_8.npz', 'backup/data_Q50k_semeai/sl_data_9.npz']
[20241016_005003] monitoring
cpu: 11.1% [0.0, 23.1, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] üî•
mem: 7.6% 
TITAN RTX, 0, 0 %, 19 MiB, 15.59 W 
TITAN RTX, 1, 0 %, 9 MiB, 0.94 W 
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:50000 (errno: 97 - Address family not supported by protocol).
üë∫network_name: DualNet_256_24_semeai is not defined.
üë∫network_name: DualNet_256_24_semeai is not defined.
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    train_main() # pylint: disable=E1120
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 107, in train_main
    train_on_gpu_ddp(program_dir=program_dir,board_size=size,  batch_size=BATCH_SIZE, epochs=EPOCHS, network_name=network_name, npz_dir=npz_dir)
  File "/data/student/u2424004/igo/TantamaGo/nn/learn.py", line 599, in train_on_gpu_ddp
    torch.multiprocessing.spawn(train_on_gpu_ddp_worker, args=(torch.cuda.device_count(), train_data_set, test_data_set, program_dir, board_size, BATCH_SIZE, EPOCHS, network_name, npz_dir), nprocs = torch.cuda.device_count(), join = True)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/student/u2424004/igo/TantamaGo/nn/learn.py", line 387, in train_on_gpu_ddp_worker
    raise(f"network_name is not defined.")
TypeError: exceptions must derive from BaseException

